# Generated by Django 5.2.11 on 2026-02-11 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BULLETIN', 'Bulletin de notes'), ('STATS', 'Export statistiques')], default='BULLETIN', max_length=10, verbose_name='Type de document')),
                ('semester', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('ANNUAL', 'Annuel')], default='S1', max_length=10, verbose_name='Semestre')),
                ('academic_year', models.CharField(help_text='Ex : 2025-2026', max_length=9, verbose_name='Année universitaire')),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Moyenne générale')),
                ('pdf_file', models.FileField(upload_to='bulletins/', verbose_name='Fichier PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='core.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('subjects', models.CharField(blank=True, default='', help_text='Séparer par des virgules. Ex : Python, Statistiques', max_length=300, verbose_name='Matières enseignées')),
                ('office_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro de bureau')),
                ('office_hours', models.CharField(blank=True, default='', help_text='Ex : Lundi 14h-16h, Mercredi 10h-12h', max_length=200, verbose_name='Horaires de permanence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='core.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('EMAIL', 'Email envoyé'), ('MEETING', 'Rendez-vous'), ('OFFICE', 'Permanence'), ('OTHER', 'Autre')], default='EMAIL', max_length=10, verbose_name='Type de contact')),
                ('subject', models.CharField(max_length=200, verbose_name='Objet / Sujet')),
                ('description', models.TextField(blank=True, default='', verbose_name='Détails')),
                ('contact_date', models.DateField(verbose_name='Date du contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='contacts.professor', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Historique de contact',
                'verbose_name_plural': 'Historiques de contacts',
                'ordering': ['-contact_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu de la note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.professor', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Note sur un professeur',
                'verbose_name_plural': 'Notes sur les professeurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
