# Generated by Django 5.2.11 on 2026-02-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='office_number',
        ),
        migrations.AddField(
            model_name='professor',
            name='other_job',
            field=models.CharField(blank=True, default='', help_text="Ex : Banquier à la BCEAO, Enseignant à l'UCAD", max_length=200, verbose_name='Métier / Lieu de travail'),
        ),
        migrations.AddField(
            model_name='professor',
            name='status',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('VACATAIRE', 'Vacataire')], default='VACATAIRE', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='office_hours',
            field=models.CharField(blank=True, default='', help_text='Ex : Lundi 14h-16h, sur rendez-vous', max_length=200, verbose_name='Disponibilités'),
        ),
    ]
