databases:
  - name: progress-db
    plan: free
    databaseName: progress_db
    region: frankfurt

services:
  - type: web
    name: progress-app
    plan: free
    runtime: python
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: progress-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: ALLOWED_HOSTS
        value: "progress-app.onrender.com"
