# Generated by Django 5.2.11 on 2026-02-10 19:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la matière')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Coefficient')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note sur 20')),
                ('grade_type', models.CharField(choices=[('DS', 'Devoir Surveillé'), ('TP', 'Travaux Pratiques'), ('EXAM', 'Examen Final'), ('ORAL', 'Examen Oral'), ('EXPOSE', 'Exposé / Présentation'), ('PROJECT', 'Projet'), ('OTHER', 'Autre')], default='DS', max_length=10, verbose_name="Type d'évaluation")),
                ('weight', models.DecimalField(decimal_places=2, help_text='Le poids de cette note dans le calcul de la moyenne', max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Poids dans la moyenne')),
                ('description', models.CharField(blank=True, default='', help_text="Ex: 'DS n°2 - Chapitre 3'", max_length=200, verbose_name='Description')),
                ('date', models.DateField(verbose_name="Date de l'évaluation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.course', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], default='L3', max_length=2, verbose_name="Niveau d'études")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.student', verbose_name='Étudiant'),
        ),
    ]
