# Generated by Django 5.2.11 on 2026-02-13 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Le pourcentage de cette évaluation dans la moyenne (ex: 20 pour 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Poids (%)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('ISEP1', 'ISEP 1'), ('ISEP2', 'ISEP 2'), ('AS1', 'AS 1'), ('AS2', 'AS 2'), ('AS3', 'AS 3'), ('ISE1CL', 'ISE 1 CL'), ('ISE1ECO', 'ISE 1 ECO'), ('ISE2', 'ISE 2'), ('ISE3', 'ISE 3'), ('MADEPP', 'Master ADEPP'), ('MAGRI', 'Master AGRI')], default='ISE1CL', max_length=10, verbose_name='Classe'),
        ),
    ]
