# Generated by Django 5.2.11 on 2026-02-13 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_grade_weight_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='weight',
            field=models.PositiveIntegerField(help_text='Le pourcentage de cette évaluation dans la moyenne (ex: 20 pour 20%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Poids (%)'),
        ),
    ]
