# Generated by Django 5.2.11 on 2026-02-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_grade_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('ISEP1', 'ISEP 1'), ('ISEP2', 'ISEP 2'), ('AS1', 'AS 1'), ('AS2', 'AS 2'), ('AS3', 'AS 3'), ('ISE1CL', 'ISE 1 CL'), ('ISE1ECO', 'ISE 1 ECO'), ('ISE1MATHS', 'ISE 1 MATHS'), ('ISE2', 'ISE 2'), ('ISE3', 'ISE 3'), ('MADEPP', 'Master ADEPP'), ('MAGRI', 'Master AGRI')], default='ISE1CL', max_length=10, verbose_name='Classe'),
        ),
    ]
