# Generated by Django 5.2.11 on 2026-02-10 19:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_average', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne visée')),
                ('semester', models.CharField(blank=True, default='', help_text="Ex: 'S1 2024-2025'", max_length=20, verbose_name='Semestre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('course', models.ForeignKey(blank=True, help_text='Laisser vide pour un objectif de moyenne générale', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.course', verbose_name='Matière')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Objectif académique',
                'verbose_name_plural': 'Objectifs académiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
