# Generated by Django 5.2.11 on 2026-02-10 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('event_type', models.CharField(choices=[('COURSE', 'Cours'), ('EXAM', 'Examen'), ('HOMEWORK', 'Devoir à rendre'), ('REVISION', 'Révision'), ('PERSONAL', 'Personnel')], default='COURSE', max_length=10, verbose_name="Type d'événement")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Toute la journée')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('reminder', models.BooleanField(default=False, verbose_name='Activer le rappel')),
                ('reminder_days', models.PositiveIntegerField(default=1, help_text="Nombre de jours avant l'événement", verbose_name='Rappel (jours avant)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
