# Generated by Django 5.2.11 on 2026-02-13 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_hours',
            field=models.PositiveIntegerField(default=0, help_text="Nombre d'heures avant l'événement (0-23)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Rappel (heures avant)'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_minutes',
            field=models.PositiveIntegerField(default=0, help_text="Nombre de minutes avant l'événement (0-59)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Rappel (minutes avant)'),
        ),
    ]
