# Generated by Django 5.2.11 on 2026-02-12 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', max_length=5, verbose_name='Thème')),
                ('font', models.CharField(choices=[('Inter', 'Inter (par défaut)'), ('Poppins', 'Poppins'), ('Nunito', 'Nunito'), ('Lora', 'Lora'), ('JetBrains Mono', 'JetBrains Mono')], default='Inter', max_length=50, verbose_name='Police')),
                ('accent_color', models.CharField(choices=[('sage', 'Vert sauge (défaut)'), ('ocean', 'Bleu océan'), ('lavender', 'Lavande'), ('peach', 'Pêche'), ('rose', 'Rose')], default='sage', max_length=20, verbose_name="Couleur d'accent")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence',
                'verbose_name_plural': 'Préférences',
            },
        ),
    ]
