# Generated by Django 5.2.11 on 2026-02-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='motivational_quote',
            field=models.CharField(blank=True, default='', help_text='Ta citation personnelle affichée sur le tableau de bord', max_length=300, verbose_name='Citation motivante'),
        ),
    ]
